import sqlite3

sql1 = '''
CREATE TABLE IF NOT EXISTS ILLUST(
ID BIGINT PRIMARY KEY NOT NULL,
TITLE TEXT NOT NULL,
TYPE BOOLEAN NOT NULL,
USERID BIGINT NOT NULL,
TAGS TEXT,
DATE DATETIME,
WIDTH INT,
HEIGHT INT,
VIEW BIGINT,
BOOKMARK BIGINT,
RATE REAL,
URLS TEXT
, UPDATETIME DATETIME)'''

sql2 = '''
CREATE TABLE IF NOT EXISTS USER(
ID BIGINT PRIMARY KEY NOT NULL,
NAME TEXT,
UPDATEILLUST DATETIME,
UPDATEFOLLOWING DATETIME
, UPDATETIME DATETIME)'''

conn = sqlite3.connect('pixiv.db')
c = conn.cursor()
c.execute(sql1)
c.execute(sql2)
conn.commit()
conn.close()
